### ISSUE TITLE
Remove warning

### ISSUE THREAD

**Issue by kpamnany** [JuliaGPU/CUDAapi.jl#105]
[This](https://github.com/JuliaGPU/CUDAapi.jl/blob/master/src/availability.jl#L53) `@warn` is creating unnecessary runtime spam for us. Can it be made an `@debug`, or removed?

Cc: @vchuravy

**Comment by maleadt** [comment]
What is the return code you're getting? I've only seen it fail with error 999, which is a bad situation worth warning about.

**Comment by kpamnany** [comment]
It's 100. In the situation it crops up, we're running on a node that has a GPU and the CUDA libraries, but we haven't requested the GPU as a resource so it is not allocated to the job.

**Comment by kpamnany** [comment]
Maybe a `usable_cuda_gpus()` function in addition to/in place of `has_cuda_gpu()` that simply returns the number of usable GPUs, which could be 0? Or -1 in case of error?
