### ISSUE TITLE
find_cuda_library("cudnn",tk) returns nothing

### ISSUE THREAD

**Issue by iuliancioarca** [JuliaGPU/CUDAapi.jl#110]
I'm having problems reinstalling Knet after a fresh install on Julia 1.4 and checked again the installation instructions. I checked my cuda libraries as usual, but `find_cuda_library `doesn't return anything.
```
tk=find_toolkit()
1-element Array{String,1}:
 "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1"

find_cuda_library("cudnn",tk)
```
I double checked my Path under Environment variables as well as the toolkit folders: the dlls are there: cudnn64_7.dll, cudart64_101.dll and cudart32_101.dll among others.

**Comment by maleadt** [comment]
Where exactly is the CUDNN DLL? Also please run with JULIA_DEBUG=CUDAapi.

**Comment by iuliancioarca** [comment]
`cudnn.lib` is in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64`
`cudnn64_7.dll` is in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin`

```
Debug: Looking for CUDA toolkit via environment variables CUDA_PATH    
└ @ CUDAapi C:\Julia-1.3.0\.julia\packages\CUDAapi\wYUAO\src\CUDAapi.jl:8
┌ Debug: Request to look for library cudnn
│   locations =
│    1-element Array{String,1}:
│     "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1"
└ @ CUDAapi C:\Julia-1.3.0\.julia\packages\CUDAapi\wYUAO\src\CUDAapi.jl:8
┌ Debug: Looking for library cudnn64, cudnn
│   locations =
│    6-element Array{String,1}:
│     "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1"
│     ⋮
│     "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\x64"
└ @ CUDAapi C:\Julia-1.3.0\.julia\packages\CUDAapi\wYUAO\src\CUDAapi.jl:8
```

Fortunately I had an older sysimage compiled for Knet, which uses:
```
CUDAapi uuid = "3895d2a7-ec45-59b8-82bb-cfc6a382f9b3"
version = "2.1.0"
```
This one works

**Comment by iuliancioarca** [comment]
Update:
It seems that `versions` variable from `find_cuda_library` is not populated.
version = "2.1.0" of CUDAapi has:
```
find_cuda_library(name::String, toolkit_dirs::Vector{String}=String[];
                  versions::Vector{VersionNumber}=reverse(get(cuda_versions, name, cuda_versions["toolkit"])),
                  kwargs...)
```
while latest version has:
```
function find_cuda_library(name::String, toolkit_dirs::Vector{String}=String[],
                           versions::Vector{VersionNumber}=VersionNumber[]; kwargs...)
```

**Comment by maleadt** [comment]
Oh sorry, forgot about that. Yes, this was the reason for the breaking 3.0 release: I removed most of the version databases in this package to lower the maintenance burden. Downstream users have to have some notion about the versions of a library that they support anyway, so I opted for having them pass that instead. For CUDNN, generally passing `[v"7"]` or whatever you require should work.

For CUDA itself, a minimal set of versions is maintained as it is required to discover the toolkit itself. You can them figure out the version of that toolkit by calling `parse_toolkit_version` with a tool that has a `--version` option (like `nvdisasm` or `ptxas`) and use that version to discover libraries that have the same version as the toolkit (CUBLAS, CUFFT, etc).
