### ISSUE TITLE
read(xxx,String) method error

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDAapi.jl#15]
I am getting method undefined errors on read(xxx,String) commands in find_host_compiler.  Are you guys testing this on 0.6.1?
```
ERROR: MethodError: no method matching read(::Cmd, ::Type{String})

```

**Comment by maleadt** [comment]
I had assumed @musm did so, as CI doesn't cover this and I don't have a Windows system to test on.

**Comment by maleadt** [comment]
How are you running CUDAapi? should be part of Compat 0.30 which is in REQUIRE
https://github.com/JuliaLang/Compat.jl/commit/f705a0f083d1dd90eab0f1e64bae9a6645ba0d2b

**Comment by denizyuret** [comment]
Sorry, you are right, read(xxx,String) works with Cmd and IO, but what we have is CmdRedirect and somebody forgot to add support for that I guess.  Since we only take what stderr writes to tmpfile and throw away stdout I will just comment out String.
