### ISSUE TITLE
more windows fixes

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDAapi.jl#20]
Tested this on:
* CUDA 9.0.176, cl.exe 19.00.24210 (VS 2015) ok
* CUDA 9.1.85, cl.exe 19.00.24210 (VS 2015) ok
* CUDA 9.1.85, cl.exe 19.12.25831 (VS 2017) could not test, CUDA 9.1 supports up to cl.exe 19.11
* vswhere does not work with lightweight build tools, must install complete VS (or not rely on vswhere)

Not sure about the interface change.  CUDAdrv etc will all be broken.  Since this package is called CUDAapi, what is the point of adding _cuda_ to function names?

discovery.jl fixes that I needed to get it working:
* L29: needs: `"$(name)$(word_size)",name])` -- otherwise find_cuda_driver does not work, which lives in `Windows/System32/nvcuda.dll`.
* L34 needs: `all_names = sort(unique(all_names), rev=true)` -- otherwise when multiple versions are present, we don't get the latest.
* L310 needs: (otherwise I get methoderror from get())
```
 program_files = get(ENV, Sys.WORD_SIZE == 64 ? "ProgramFiles(x86)" : "ProgramFiles",
                            Sys.WORD_SIZE == 64 ? "C:\\Program Files (x86)" : "C:\\Program Files")
```
* L328 needs: `isempty(msvc_paths) && error("No Visual Studio installation found")`, I think this one is just a typo.

Latest Amazon AWS machine image: ami-263e1643, Knet171216win at Ohio (us-east-2) running on a p2.xlarge instance.

**Comment by maleadt** [comment]
> vswhere does not work with lightweight build tools, must install complete VS (or not rely on vswhere)

We can download `vswhere` if we start to rely on it.

> CUDAdrv etc will all be broken.

Well, no, we just push an upper bound and fix the 2 usages of the API.

> Since this package is called CUDAapi, what is the point of adding cuda to function names?

Consistency, as its `find_library` + `find_cuda_library`. But yeah, we can keep `find_toolkit` if you feel strongly about it.

I'll have a look at your proposed fixes tomorrow, but in general just propose a PR instead of listing them.

**Comment by denizyuret** [comment]
I don't know how to (1) send a PR, (2) not put why I did what I did in
comments, and (3) somehow let you know why I changed things.

**Comment by maleadt** [comment]
Yeah, the git workflow breaks down a little in that case. I typically self-comment using the Github UI to explain rationale, or use extended commit messages.

No worries though, I'll have a look tomorrow. Thanks for verifying on a variety of systems.
