### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAapi.jl#4]
cc @denizyuret

**Comment by quaertym** [comment]
This can be related:

I am working on windows support for [Knet.jl](https://github.com/denizyuret/Knet.jl). I tried to build `CUDAdrv.jl` on windows and it uses `discovery.jl` of `CUDAapi.jl` . I realized that `names` in this [line](https://github.com/JuliaGPU/CUDAapi.jl/blob/master/src/discovery.jl#L42) should include `nvcuda` but it is not there. I fixed it by manually adding it. If you can guide me, I can submit a PR for this.

**Comment by maleadt** [comment]
No, `nvcuda` was already being searched for:
https://github.com/JuliaGPU/CUDAapi.jl/blob/31063fa208d11bad8b185c38372d660c60699a5d/src/discovery.jl#L9

The problem was more complicated, see #10 

The only thing I haven't been able to fix, is `cl.exe` discovery. Even after (instructing the user to) source `vcvarsall.bat`, I can't manage to deduce the location of `cl.exe` from the environment variables. The heuristics @musm has added don't seem to work on Community 2017 anymore.
I'm thinking of just having the user put `cl.exe` in his PATH, and be done with it. If there's no easy way to discover `cl.exe`, we shouldn't be trying to:

https://github.com/JuliaGPU/CUDAapi.jl/blob/58bcab6ced8b1d92b2453f8dd6d60778c4c35eab/src/discovery.jl#L293-L298

**Comment by musm** [comment]
https://github.com/Microsoft/vswhere

is needed for newer vc studio installations, which is in  included in the 2017 visual studio installation, and can be used to find `CL.exe`

CUDA 9 is required for  VC2017 support

**Comment by musm** [comment]
Also see https://github.com/JuliaGPU/CUDArt.jl/issues/70

**Comment by maleadt** [comment]
Right, but how do I get the actual path to `cl.exe` from that. Sure, it'll help to find or activate a prompt with the VS vars sourced, but even in that prompt `cl.exe` doesn't seem discoverable.

And yes, CUDAapi needs a compatibility database for matching VS versions to CUDA versions.

**Comment by musm** [comment]
vsdevcmd.bat   has cl sourced   (I just tried it)

https://github.com/Microsoft/vswhere/wiki/Find-VC

**Comment by maleadt** [comment]
Mine doesn't, I must be missing a part of VS then.

Can you confirm this picks up the path to `cl.exe`?

```julia
vswhere = download("https://github.com/Microsoft/vswhere/releases/download/2.2.11/vswhere.exe")

vs_install_path = chomp(readstring(`$vswhere  -latest -property installationPath`))
if !isdir(vs_install_path)
    error("Cannot find a proper Visual Studio installation. Make sure Visual Studio is installed.")
end

vs_version_major = parse(split(chomp(readstring(`$vswhere  -latest -property installationVersion`)), '.')[1])
if vs_version_major >= 15
    vs_cmd_prompt = joinpath(vs_install_path, "VC", "Auxiliary", "Build", "vcvarsall.bat")
else
    vs_cmd_prompt = joinpath(vs_install_path, "VC", "vcvarsall.bat")
end

# check whether 32 or 64 bit archtecture
# NOTE: Actually, nvcc in x86 visual studio command prompt doesn't make 32-bit binary
#       It depends on whether CUDA toolkit is 32bit or 64bit
if Int == Int64
    arch = "amd64"
else
    arch = "x86"
end

run(`cmd /C "$vs_cmd_prompt" $arch \& where cl.exe`)
```

EDIT: yeah seems to work here after installing a boatload of VC++ tools. Figured I only needed the compiler, apparently not.

**Comment by maleadt** [comment]
@quaertym: the changes to CUDAapi in #10 should fix Windows support. What remains for Knet, from a quick first glance, is that the Knet package build scripts calls out to `make` instead of building directly. But you can pretty easily recreate that in Julia, see e.g.: https://github.com/JuliaGPU/CUDArt.jl/blob/51ada407672d779ee11e69ad3cbd2642364b1330/deps/build.jl#L58-L77
(but don't use the `logging_run` because I'll be removing that from CUDAapi)

**Comment by quaertym** [comment]
@maleadt Thanks. My problem was getting `nvcuda.dll` without versions at the end. #10 seems like a fix.
