### ISSUE TITLE
Support non-english installation?

### ISSUE THREAD

**Issue by ylxdzsw** [JuliaGPU/CUDAapi.jl#49]
I have a Chinese version of Visual Studio installed, and CUDAapi.jl cannot recognize it:

```
julia> using CUDAapi
INFO: Recompiling stale cache file C:\Users\ylxdzsw\.julia\lib\v0.6\CUDAapi.ji for module CUDAapi.

julia> CUDAapi.find_host_compiler()
ERROR: MethodError: no method matching getindex(::Void, ::Int64)
Stacktrace:
 [1] find_host_compiler(::Void) at C:\Users\ylxdzsw\.julia\v0.6\CUDAapi\src\discovery.jl:409
 [2] find_host_compiler() at C:\Users\ylxdzsw\.julia\v0.6\CUDAapi\src\discovery.jl:322
```

I think the problem is in the reg match, where it searches for "Version"

```
# find MSVC versions
msvc_list = Dict{VersionNumber,String}()
for path in msvc_paths
    tmpfile = tempname() # TODO: do this with a pipe
    if !success(pipeline(`$path`, stdout=DevNull, stderr=tmpfile))
        warn("Could not execute $path")
        continue
    end
    ver_str = match(r"Version\s+(\d+(\.\d+)?(\.\d+)?)"i, read(tmpfile, String))[1]
    ver = VersionNumber(ver_str)
    msvc_list[ver] = path
end
```

but my `cl.exe` outputs something funnier:

```
$ cl.exe
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.14.26431 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]
```

I would suggest use `r"(\d+(\.\d+)(\.\d+)?)"i` instead. Not sure how robust will this be.

**Comment by maleadt** [comment]
That's not very robust indeed, but I could add that as a second regex.
I take it you are interested in having this fixed on the 0.6-compatible branch?

**Comment by ylxdzsw** [comment]
I would be fine with whatever since I have to modify the file anyway: my `vswhere` cannot find my installation and I don't know why, so I must provide the path manually. Maybe we can also search "cl.exe" in the PATH to locate MSVC?

**Comment by maleadt** [comment]
Does #50 help? Implemented both the secondary regex and your PATH suggestion.

**Comment by ylxdzsw** [comment]
Wow, Thanks!
