### ISSUE TITLE
CI does not spot: libcudadevrt.lib is actually cudadevrt.lib on windows

### ISSUE THREAD

**Issue by musm** [JuliaGPU/CUDAapi.jl#70]

**Comment by maleadt** [comment]
Mind if you fix and test this one-line change? I don't have a Windows system, and I'm not sure why CI didn't flag this... CI should probably also run with JULIA_DEBUG=CUDAapi to debug issues,

**Comment by musm** [comment]
Not sure, but I can submit a PR  and test this.

**Comment by musm** [comment]
@maleadt  
Let me get this straight.   `find_libcudadevrt` tries to find the STATIC  lib file?  Is the  shared library (dll) needed ?

**Comment by maleadt** [comment]
>  Let me get this straight. find_libcudadevrt tries to find the STATIC lib file? Is the shared library (dll) needed ?

I've only ever encountered a static (.a) on Linux -- it's supposed to contain PTX code, so I'm not sure a dll makes sense there.
