### ISSUE TITLE
Longer term goal with other CUDA libraries

### ISSUE THREAD

**Issue by musm** [JuliaGPU/CUDAapi.jl#79]
Longer term how should this library  be used for other packages in the CUDA ecosystem ?

**Comment by maleadt** [comment]
What do you mean? The README is pretty explicit, no?

> Reusable components for CUDA API development.
>
> This package provides some reusable functionality for programming against CUDA or NVIDIA APIs.

Discovery is one (important) element, but there's other opportunities too, e.g. the library_types.

**Comment by musm** [comment]
Does Nvidia allow us to distributing the CUDA toolkit?

**Comment by maleadt** [comment]
Only [certain parts](https://docs.nvidia.com/cuda/eula/index.html#attachment-a) of the toolkit are redistributable, and we currently rely on tools (nvdisasm, ptxas for CUDAnative) and libraries (cudnn for CuArrays) that aren't part of that list. Furthermore, we still need the NVIDIA driver, which is almost  impossible to distribute / set-up from Julia. Nonetheless, CUDAapi would be a good place to experiment with that and implement the necessary functionality.

**Comment by musm** [comment]
I see, thanks for the discussion. Yes it would be interesting to see if we could distributing the parts that are allowable, if the libraries are missing from the user host PC. Closing in favor of more specific issues.
