### ISSUE TITLE
Discovery fails if CUDA env vars are set to empty variable

### ISSUE THREAD

**Issue by maximumcats** [JuliaGPU/CUDAapi.jl#87]
If I have `CUDA_PATH` in my environment but set as an empty variable, CUDA discovery will fail.
```
$ env | grep CUDA
CUDA_PATH=
```
In this case, `find_toolkit()` will return an empty list. This will then fail in `find_toolkit_version()` when building the CUDAnative package:
```
┌ Error: Error building `CUDAnative`:
│ ERROR: LoadError: CUDA toolkit at  doesn't contain nvcc
```
The problem is that the code that checks if these env vars exist will return immediately even if the env vars are empty:

https://github.com/JuliaGPU/CUDAapi.jl/blob/v1.0.1/src/discovery.jl#L230-L241

So this code block should check if the environment variables have a valid value, and if not, pass on to the remainder of the function to check the nvcc path and the default system paths.

**Comment by maleadt** [comment]
Yeah, this should be fixed. Will have a look.

Is there any reason you have an empty `CUDA_PATH` set? Does it carry any meaning?

**Comment by maximumcats** [comment]
No, it was pure bad luck on my part -- my .bashrc file happens to set CUDA_PATH to something meaningful if I'm on a system where I know in advance that CUDA is installed, and (apparently) to an empty variable if not. On the system where I was running when I ran into this, I hadn't yet told this script where CUDA is installed on that system.
